apiVersion: v1
kind: Service
metadata:
  name: wcsportal-svc
spec:
  type: NodePort
  selector:
    app: wcsportal
  ports:
    - port: 80
      targetPort: 5000
      nodePort: {{ .Values.nodePort }}